version: '3.1'
services:
  db:
    image: mysql
    container_name: springboot2_essentials_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - devdojo_data:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - mysql-compose-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    #pega o arquivo prometheus.yml que criamos, copia para o container na pasta etc/prometheus
    volumes:
      - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
    #executa um comando executando o arquivo de configuração que inserimos
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

volumes:
  devdojo_data:

networks:
  mysql-compose-network:
    driver: bridge