server:
  error:
    include-stacktrace: on_param
  port: 8081 #alterada porta da aplicação

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update #Todas as vezes que iniciar a aplicação ira atualizar o banco
    show-sql: true #mostra no console a query SQL que esta sendo executada pelo JPA